version: "3.8"
services:
  
  frontend:
    restart: always
    image: alexheld/plant-controller-frontend:latest
    container_name: plant-controller-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - postgres
      - backend
  
  backend:
    restart: always
    image: alexheld/plant-controller-backend:latest
    container_name: plant-controller-backend
    build:
      context: server
      dockerfile: Dockerfile
    environment:
      - LOG_LEVEL=debug
      - PG_URL=postgres://postgres:postgres@postgres:5432/plant-controller?sslmode=disable
      - HTTP_ADDR=:8080
    ports:
    - 8080:8080
    depends_on:
      - postgres

  
  postgres:
    restart: always
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=plant-controller
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
