version: "3.7"
services:
  
  postgres:
    restart: always
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=plant-controller
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
