version: "3.7"
services:
  app:
    build: .
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      profile: prod
  db:
    image: mongo:4.2.3
    container_name: db
    environment:
      MONGO_INITDB_DATABASE: tech
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init.js


  rest-api:
    environment:
      - HTTP_ADDR=:8080
      - FILE_PATH=../../files
      - PG_URL=postgres://postgres:postgres@postgres/restapi?sslmode=disable
      - PG_MIGRATIONS_PATH=file://../../store/pg/migrations
      - LOG_LEVEL=debug
    build: ./
    command: [ "./wait-for-it.sh", "postgres:5432", "--timeout=60", "--", "./rest-api" ]
    ports:
      - 8080:8080
    depends_on:
      - postgres

      
      
  postgres:
    restart: always
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=plant-controller
    volumes:
      - ./data/pg:/var/lib/postgresql/data

